name: "Автоматическое обновление пакетов NixOS"

on:
  schedule:
    - cron: '0 3 */3 * *'
  workflow_dispatch:

jobs:
  update-flake:
    name: "Обновление flake.lock"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Клонирование репозитория"
        uses: actions/checkout@v4

      - name: "Установка Nix"
        uses: DeterminateSystems/nix-installer-action@v12

      - name: "Обновление зависимостей (flake update)"
        run: |
          # Поиск директории с flake.nix
          FLAKE_FILE=$(find . -name "flake.nix" | head -n 1)
          if [ -z "$FLAKE_FILE" ]; then
            echo "Ошибка: файл flake.nix не найден"
            exit 1
          fi
          FLAKE_DIR=$(dirname "$FLAKE_FILE")
          echo "Файл flake.nix найден в директории: $FLAKE_DIR"

          # Заходим в директорию с флейком
          cd "$FLAKE_DIR"

          # Создание временных заглушек для импортов
          touch hardware-configuration.nix
          echo "{ ... }: { }" > hardware-configuration.nix
          touch users.nix
          echo "{ ... }: { }" > users.nix
          touch rutoken.nix
          echo "{ ... }: { }" > rutoken.nix

          # Обновление flake.lock (запуск внутри директории)
          nix flake update --extra-experimental-features "nix-command flakes"

          # Удаление заглушек
          rm hardware-configuration.nix users.nix rutoken.nix

      - name: "Сохранение изменений в GitHub"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Поиск и добавление обновленного flake.lock
          find . -name "flake.lock" -exec git add {} +
          
          git commit -m "система: автоматическое обновление flake.lock" || echo "Нет изменений для коммита"
          git push
