name: "NIX_AUTO_REPAIR_SERVICE"

on:
  schedule:
    - cron: '0 3 */3 * *'
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: STEP_1_CHECKOUT
        uses: actions/checkout@v4

      - name: STEP_2_INSTALL_NIX
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          use-github-cache: false

      - name: STEP_3_DEBUG_FILES
        run: |
          echo "Я ВИЖУ ЭТИ ФАЙЛЫ:"
          find . -maxdepth 3 -not -path '*/.*'

      - name: STEP_4_ACTUAL_UPDATE
        run: |
          # Ищем flake.nix
          FLAKE_FILE=$(find . -name "flake.nix" | head -n 1)
          
          if [ -z "$FLAKE_FILE" ]; then
            echo "ОШИБКА: flake.nix НЕ НАЙДЕН!"
            exit 1
          fi
          
          FLAKE_DIR=$(dirname "$FLAKE_FILE")
          echo "РАБОТАЮ В ПАПКЕ: $FLAKE_DIR"
          
          # Создаем все заглушки
          touch "$FLAKE_DIR/hardware-configuration.nix"
          echo "{ ... }: { }" > "$FLAKE_DIR/hardware-configuration.nix"
          touch "$FLAKE_DIR/users.nix"
          echo "{ ... }: { }" > "$FLAKE_DIR/users.nix"
          touch "$FLAKE_DIR/rutoken.nix"
          echo "{ ... }: { }" > "$FLAKE_DIR/rutoken.nix"
          
          # Запуск
          nix flake update "$FLAKE_DIR" --extra-experimental-features "nix-command flakes"
          
          # Удаление
          rm "$FLAKE_DIR/hardware-configuration.nix" "$FLAKE_DIR/users.nix" "$FLAKE_DIR/rutoken.nix"

      - name: STEP_5_PUSH_CHANGES
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          find . -name "flake.lock" -exec git add {} +
          git commit -m "system: auto-update flake.lock" || echo "No changes to commit"
          git push
